### ISSUE TITLE
In my one tab  inside viewpager with 3 tab. then how to add new fragment from click event of viewpager fragment

### ISSUE THREAD

**Issue by ghost** [Emre-Kalkan/InstagramLIKEBackStack#2]

**Comment by Emre-Kalkan** [comment]
Hello. I am sorry but i could not fully understand what you want. If your goal is to do same back action with tabs then create new Stack<> for tabs and when you open new tab add new item to your stack. When back pressed select the previos tab from stack and show it. Hope it helps.

**Comment by ghost** [comment]
Let's assume i have 3 tab. in home tab inside 2 tab with viewpager. now i want to add fragment inside child tab item click event. but it goes error like can't find id for fragment. because in 2nd tab i have 2 fragment and that both fragment is new initialised. so in this case root fragment id can't found when user add new fragment from 2nd tab item click event.

**Comment by Emre-Kalkan** [comment]
You should ask this question in stackoverflow with showing codes and errors.
